const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
require('./test_data_preservation.cjs')(root, path.join(root, 'preview-checks/before-browse-toolbar-20260909'));
async function ids(page) { return page.evaluate(() => getFilteredItems(true).map(item => item.id).sort()); }
async function rules(page) {
  await page.locator('.nav [data-page-target="methodology"]').click();
  await page.locator('[data-methodology-target="region-classification"]').click();
}
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const results = [];
  try {
    for (const [width, file] of [[1440, 'web/index.html'], [390, 'web/index.html'], [1440, 'share/acro_ai_hot_tracker_dashboard.html']]) {
      const page = await browser.newPage({ viewport: { width, height: 1000 } });
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.route(/^https?:/, route => route.abort());
      await page.goto(pathToFileURL(path.join(root, file)).href);
      await page.waitForFunction(() => document.querySelector('.fusion-region-coverage'));
      assert.equal(await page.locator('#tierFilter').isVisible(), false);
      assert.deepEqual(await page.locator('[data-browse]').allTextContents(), ['总览', '周看板', '月看板', '全部记录']);
      assert.equal(await page.locator('.toolbar #fusionProduct').isVisible(), true);
      assert.equal(await page.locator('.toolbar #fusionRegionControl').isVisible(), true);
      assert.equal(await page.locator('#regionPanel [data-fusion-region-rules]').count(), 0);
      assert.doesNotMatch(await page.locator('#regionPanel').innerText(), /准入|逐条判读|需补原文|规则版本/);
      assert.doesNotMatch(await page.locator('#fusionScope').innerText(), /进入日报|即时提醒|归档观察/);
      assert.doesNotMatch(await page.locator('main').innerText(), /进入日报|即时提醒|归档观察/);
      assert.equal(await page.locator('[data-page="overview"] .meta-row .tag.daily').count(), 0);
      const baseline = await ids(page);
      assert.equal(baseline.length, 66);
      const label = `${width}-${file.startsWith('web') ? 'web' : 'share'}`;
      await page.locator('.topbar').screenshot({ path: path.join(root, `preview-checks/browse-toolbar-${label}.png`) });
      await page.locator('#regionPanel').screenshot({ path: path.join(root, `preview-checks/browse-regions-${label}.png`) });
      const topic = await page.evaluate(() => getFilteredItems(true).filter(item => fusionRegions(item).includes('japan')).flatMap(fusionTopics).find(topic => topic !== 'unidentified'));
      assert.ok(topic);
      const expected = await page.evaluate(topic => getFilteredItems(true).filter(item => fusionTopics(item).includes(topic) && fusionRegions(item).includes('japan')).map(item => item.id).sort(), topic);
      await page.locator('#fusionProduct').selectOption(topic);
      await page.locator('#fusionRegionLabel').click();
      await page.locator('[data-fusion-region][value="japan"]').check();
      await page.locator('#fusionRegionLabel').click();
      assert.deepEqual(await ids(page), expected);
      assert.equal(Number(await page.locator('[data-fusion-all] strong').first().innerText()), expected.length);
      assert.equal(await page.evaluate(() => [...document.querySelectorAll('[data-fusion-region-detail]')].every(el => +el.querySelector('strong').textContent === getFilteredItems(true).filter(item => fusionRegions(item).includes(el.dataset.fusionRegionDetail)).length)), true);
      await page.locator('[data-browse="month"]').click();
      await page.locator('#boardMonthDate').fill('2026-08');
      assert.equal(await page.evaluate(() => periodView.topic), topic);
      assert.deepEqual(await page.evaluate(() => periodView.regions), ['japan']);
      assert.equal(await page.evaluate(() => boardItems().every(event => event.topics.includes(periodView.topic) && event.regions.includes('japan'))), true);
      await page.locator('[data-browse="week"]').click();
      assert.equal(await page.locator('[data-browse="week"]').getAttribute('aria-current'), 'page');
      await page.locator('[data-browse="overview"]').click();
      assert.deepEqual(await ids(page), expected);
      await page.locator('#fusionProduct').selectOption('all');
      await page.locator('#fusionRegionLabel').click();
      await page.locator('[data-fusion-regions-clear]').click();
      await page.locator('#fusionRegionLabel').click();
      assert.deepEqual(await ids(page), baseline);
      await page.locator('[data-time-range="90"]').click();
      const apac = await page.evaluate(() => window.AIHOT_REGION_MODEL.distribution(getFilteredItems(true))[0].items.map(item => item.id).sort());
      await page.locator('[data-fusion-region-family="apac"]').click();
      assert.deepEqual(await page.evaluate(() => [...fusion.detail.ids].sort()), apac);
      await page.locator('#fusionEvidence [data-fusion-back]').click();
      await rules(page);
      assert.match(await page.locator('#methodologyDetailBar').innerText(), /分类与业务输出.*地区判读与统计/s);
      assert.match(await page.locator('#regionRulesContent').innerText(), /会议.*会址/s);
      const pending = Number(await page.locator('[data-fusion-region-review="pending"] strong').innerText());
      assert.equal(pending, 4);
      await page.locator('[data-fusion-region-review="pending"]').click();
      assert.equal(await page.locator('#fusionEvidenceCards .signal-card').count(), 4);
      await page.locator('#fusionEvidence [data-fusion-region-rules]').click();
      assert.equal(await page.locator('#metric-region-classification').isVisible(), true);
      await page.locator('#fusionRegionMode').selectOption('content');
      assert.equal(await page.evaluate(() => fusion.regionMode), 'content');
      await page.locator('#fusionRegionMode').selectOption('reviewed');
      await page.locator('#methodologyBackButton').click();
      await page.locator('.nav [data-page-target="overview"]').click();
      await page.locator('[data-browse="records"]').click();
      const historyCount = await page.evaluate(() => boardItems().length);
      assert.ok(historyCount > 146);
      assert.equal(await page.evaluate(() => boardItems().some(event => event.reports.some(item => item.tier === 'archive'))), true);
      assert.equal(Number(await page.locator('[data-board-result-count]').getAttribute('data-board-result-count')), historyCount);
      assert.equal(await page.locator('#periodControls .board-period-toolbar').isVisible(), false);
      assert.match(await page.locator('#periodDetail').innerText(), /全部已保留历史/);
      await page.locator('#periodDetail [data-board-event]').first().click();
      assert.ok(await page.locator('.board-evidence-links a').count());
      await page.locator('[data-board-back]').click();
      assert.equal(Number(await page.locator('[data-board-result-count]').getAttribute('data-board-result-count')), historyCount);
      await page.reload();
      await page.waitForFunction(() => document.querySelector('[data-board-result-count]'));
      assert.equal(Number(await page.locator('[data-board-result-count]').getAttribute('data-board-result-count')), historyCount);
      await page.locator('[data-board-back]').click();
      assert.equal(await page.locator('[data-browse="overview"]').getAttribute('aria-current'), 'page');
      assert.deepEqual(errors, []);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
      results.push({ width, file, defaultNews: baseline.length, productAndJapan: expected.length, apac90: apac.length, pending90: pending, retainedEvents: historyCount });
      console.log(`PASS ${label}: four views, product/region intersections, rules relocation, evidence drilldowns, archive navigation, reload and responsive layout.`);
      await page.close();
    }
    fs.writeFileSync(path.join(root, 'preview-checks/browse-controls-results.json'), JSON.stringify({ date: '2026-09-09', results }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
